form:
  fields:
    _site:
      type: section
      title: PLUGIN_ADMIN.PAGE_ACCESS
      underline: true

      fields:

        header.visibility_requires_access:
          type: toggle
          toggleable: true
          label: PLUGIN_ADMIN.PAGE_VISIBILITY_REQUIRES_ACCESS
          help: PLUGIN_ADMIN.PAGE_VISIBILITY_REQUIRES_ACCESS_HELP
          highlight: 0
          options:
            1: PLUGIN_ADMIN.YES
            0: PLUGIN_ADMIN.NO
          validate:
            type: bool


        header.page_access:
          type: page_access
          label: PLUGIN_ADMIN.PAGE_ACCESS
          help: PLUGIN_ADMIN.PAGE_ACCESS_HELP
          ignore_empty: true
          validate:
            type: array
            value_type: bool

        header.access:
          type: permissions
          toggleable: true
          label: PLUGIN_ADMIN.PAGE_ACCESS
          help: PLUGIN_ADMIN.PAGE_ACCESS_HELP
          ignore_empty: true
          validate:
            type: array
            value_type: bool

    _admin:
      type: section
      title: PLUGIN_ADMIN.PAGE PERMISSIONS
      underline: true

      fields:

        header.permissions.inherit:
          type: toggle
          toggleable: true
          label: PLUGIN_ADMIN.PAGE_INHERIT_PERMISSIONS
          help: PLUGIN_ADMIN.PAGE_INHERIT_PERMISSIONS_HELP
          highlight: 1
          options:
            1: PLUGIN_ADMIN.YES
            0: PLUGIN_ADMIN.NO
          validate:
            type: bool

        header.permissions.authors:
          type: list
          toggleable: true
          label: PLUGIN_ADMIN.PAGE_AUTHORS
          help: PLUGIN_ADMIN.PAGE_AUTHORS_HELP

          fields:
            value:
              type: text
              placeholder: PLUGIN_ADMIN.USERNAME
              style: vertical

        header.permissions.groups:
          type: array
          toggleable: true
          label: PLUGIN_ADMIN.PAGE_GROUPS
          help: PLUGIN_ADMIN.PAGE_GROUPS_HELP
